version: '3'

services:
  pushgateway:
    image: 'prom/pushgateway'
    ports:
      - '9091:9091'
    env_file:
      - .env

  prometheus:
    image: 'prom/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'    
    depends_on:
      - pushgateway
    env_file:
      - .env

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 9092:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
  
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pushgateway
      - prometheus
      - grafana
    env_file:
      - .env

volumes:
  prometheus_data:
  grafana_data:
