version: '3'

services:
  pushgateway:
    image: 'prom/pushgateway'
    ports:
      - '9091:9091'
    env_file:
      - .env

  prometheus:
    image: 'prom/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'    
    depends_on:
      - pushgateway
    env_file:
      - .env

volumes:
    prometheus_data:
